import {
  Geist,
  Geist_Mono,
  Mukta_Malar,
  Poppins,
  Tauri,
} from "next/font/google";
import "./globals.css";
import NavabarSection from "@/Components/NavabarSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tauri = Tauri({
  variable: "--font-tauri",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      supresshydrationwarning="true"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${tauri.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavabarSection />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
